### PR TITLE
Fix parsing of '((1, 2),)'

### PR DESCRIPTION
**Pull request by kmod**
Previously would parse as '(1, 2)' (ie with the outer tuple nesting
removed).

### CODE REVIEW

**Comment by kmod** [comment]
hmm sorry this PR is definitely wrong, since it now parses `(1,2,)` as `((1,2),)`.  could you help take a look?

**Comment by kmod** [comment]
Ok, updated it and I think this is better.  I think the issue before is that `testlist_comp` and `atom` would both do some amount of work around dealing with tuples, but testlist_comp wouldn't pass enough information back for atom to distinguish between the cases of a single tuple element vs parsing it as a tuple.  So I just moved all the logic into testlist_comp which I think makes things simpler.  It feels weird that the `if(testlist_comp())` branch doesn't have any code in it -- is there a different way of doing it?

**Comment by undingen** [comment]
I just ran into the same issue with pycrypto and can confirm that this fixed the issue.

**Comment by vinzenz** [comment]
> It feels weird that the if(testlist_comp()) branch doesn't have any code in it -- should there be?

From my memory I think this was to solve the issue with the else if conditions, if testlist_comp fails, then it'll still try the next ones. 
Not really a beauty, but well it worked -_-'

**Comment by vinzenz** [comment]
Thanks a lot for finding and fixing this!

**Pull request merged**
